name: contacts_service
description: A Flutter plugin to retrieve and manage contacts on Android and iOS devices.
version: 0.6.3
homepage: https://github.com/lukasgit/flutter_contacts
maintainer: Lukas Dickie (@lukasgit)

environment:
  sdk: ^3.9.0
  flutter: ^3.35.4

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1
  quiver: ^3.2.2

flutter:
  plugin:
    platforms:
      android:
        package: flutter.plugins.contactsservice.contactsservice
        pluginClass: ContactsServicePlugin
      ios:
        pluginClass: ContactsServicePlugin

dev_dependencies:
  flutter_test:
    sdk: flutter
